### ISSUE TITLE
Omzetten naar React/Angular/Vue

### ISSUE THREAD

**Issue by GillesPl** [NMCT/Website#14]
Zorgt ervoor dat de website modulair & schaalbaar wordt.
 + data integratie is gemakkelijker

**Comment by GillesPl** [comment]
Kan dit doen na m'n examens als een project

**Comment by MLoth** [comment]
Hey Gillles! Bedankt, maar dat is echt niet nodig. We gaan toch richting een Wordpress en in eerste instantie PHP.
Het zou goed zijn voor jou om alle bestanden op GitHub te zetten en dan gaan wij er verder mee aan de slag 😉.
Volgende week donderdag zal ik het project bekijken en jouw todo's overlopen en opnieuw verdelen tussen @simoncoudeville en mezelf.
Hartelijk dank voor de hulp!
