### ISSUE TITLE
Hamburger menu + notification jump

### ISSUE THREAD

**Issue by simoncoudeville** [NMCT/Website#30]

**Comment by simoncoudeville** [comment]
Heb jij dat al gedaan? Ik zie dat precies nergens. Een oplossing zou kunnen zijn om de notification ook nog eens in de mobile nav te steken.

**Comment by MLoth** [comment]
Ga ik dus voor kijken zoals gezegd. Er was een stukje JS hiervoor, maar dat is weg... 😆
